### ISSUE TITLE
Access to the temporary path "/GleamTech/AssemblyResolver" is denied due to insufficient permissions

### ISSUE THREAD

**Issue by joee7** [GleamTech/DocumentUltimate#14]
How to give access to temporary path when we run .NET core app on docker container using Document Ultimate. We would like to use Azure Blob Storage as cache location. 

In addition we noticed its creating GleamTech/AssemblyResolver folder inside root folder in local. but its unable to create when we run on a docker container. Any directions will help to continue use Document Ultimate.

Error Message: 
---> System.TypeInitializationException: The type initializer for 'GleamTech.AssemblyResolver.AssemblyResolver' threw an exception.
---> GleamTech.IO.TemporaryPathException: Access to the temporary path "/GleamTech/AssemblyResolver" is denied due to insufficient permissions.
If you are using impersonation, add any impersonated user (including IUSR) to IIS_IUSRS group which should already have access to temporary path by default. After the change, run 'iisreset' in Administrator Command Prompt.
---> System.UnauthorizedAccessException: Access to the path '/GleamTech/AssemblyResolver' is denied.
---> System.IO.IOException: Permission denied
--- End of inner exception stack trace ---
at System.IO.FileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at GleamTech.IO.TemporaryFolder.Access()
--- End of inner exception stack trace ---
at GleamTech.IO.TemporaryFolder.Access()
at GleamTech.AssemblyResolver.AssemblyResolver..cctor()
--- End of inner exception stack trace ---
at GleamTech.AssemblyResolver.AssemblyResolver.Register(Assembly primaryAssembly, String configurationResourceName, String configurationVersion)
at AssemblyBootstrap.Register()
at AssemblyBootstrap.Initialize()
at .cctor()
--- End of inner exception stack trace ---

**Comment by GleamTech** [comment]
https://stackoverflow.com/questions/45972608/how-to-give-folder-permissions-inside-a-docker-container-folder
