### ISSUE TITLE
Document Ultimate - Need to confirm if it will work in Linux Container - Urgent!

### ISSUE THREAD

**Issue by rajjos** [GleamTech/DocumentUltimate#15]
The below error occurs after our code is migrated from .Net Framework to .NET 6.0 and deployed in a Linux Container. Do you support Document Viewer in Linux Container. 

In addition the cache location is setup as Azure Storage Account.

**Error Message**: “PortableEngine is currently supported only on Windows platform.”.

![image](https://github.com/GleamTech/DocumentUltimate/assets/66692880/6e8fbc4f-8a1e-4f5c-bdc5-c99848ab3723)

**Comment by GleamTech** [comment]
We support Linux Container partially, PDF conversion currently needs Windows and DocumentViewer depends on PDF conversion so it displays this error. Other conversions work on Linux Container, for example if you use DocumentConverter. However soon we will support PDF conversion, so DocumentViewer in Linux Container, I will let you know.

**Comment by rajjos** [comment]
@GleamTech team - Is there an earliest available date or timeline to support PDF conversion in Linux Container. 

Would **GleamTech Ultimate Viewer** need PDF conversion for Linux container to make it work for Microsoft Office such as .docx or .xlsx.

**Comment by GleamTech** [comment]
We plan to support it soon, in few weeks. We already released a major version which has a new advanced DocumentViewer UI, so it took time. Next, we will complete linux support

![image](https://github.com/user-attachments/assets/30a5de57-5655-44e2-b408-de50376d2da1)
![image](https://github.com/user-attachments/assets/2714bbf2-fac4-4c66-9435-75357281e424)

**Comment by rajjos** [comment]
Great to know about the advanced Document Viewer UI released recently. Hope this advanced viewer supported to use within .NET Core MVC 8.0 Application.
