### ISSUE TITLE
Format of the initialization string does not conform to specification starting at index 0

### ISSUE THREAD

**Issue by TomasBouda** [GleamTech/DocumentUltimate#3]
I'm using your library DocumentUltimate(trial) in ASP.NET MVC app. When I launch the application it fails on `Application_Start` with 
```
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0
StackTrace:
   in System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 
currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
```
Any idea whats the problem? I've set up everythig according to your manual here on github. 
Thank you

**Comment by GleamTech** [comment]
It's seems you are setting CacheLocation property to an invalid string, e.g. do you have some weird characters or all white space in the value? Check what you are setting via these options:

```xml
<add key="DocumentUltimateWeb:CacheLocation" value="~/App_Data/DocumentCache" />
```

```c#
DocumentUltimateWebConfiguration.Current.CacheLocation = "~/App_Data/DocumentCache";
```

**Comment by TomasBouda** [comment]
Thanks for reply. I tried exactly your code
```cs
DocumentUltimateWebConfiguration.Current.CacheLocation = "~/App_Data/DocumentCache";
```
but it still, fails on this line with same message. Seems that this issue is related to some setting in our project because I tried to create new solution and it works fine there. I will dig down and reply back if I find the cause :smirk:

**Comment by GleamTech** [comment]
That's strange. `Location` class internally uses `System.Data.Common.DbConnectionStringBuilder` for parsing location string for multiple filesystems (Physical, Amazon S3, Azure Blob) because they look like connection strings and I don't know why `DbConnectionStringBuilder` would fail because of unrelated settings (first time I see this error). My guess is you have Entity Framework in your project, please check `<connectionStrings>` and `<entityFramework>` tags in your Web.config:
https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework60.html

Please also see here for possible solutions:
https://stackoverflow.com/questions/9040266/how-to-fix-error-format-of-the-initialization-string-does-not-conform-to-speci

Let me know.

**Comment by TomasBouda** [comment]
I still didn't found where the problem is, but I've found one thing... previously I didn't try to skip the exception(click continue in vs) which is kinda silly :blush: When I do that, app runs fine and document viewer works like charm. So except that ArgumentException on start there is no problem. It still bothers me a bit but I guess it's not a big deal. Thanks for your help.
Just for the record, here is our connectionString:
```xml
<add name="Entities" connectionString="metadata=res://*/;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=.;Initial Catalog=FairCreditDev;Integrated Security=False;User=FairCredit;Password=***;MultipleActiveResultSets=True&quot;" providerName="System.Data.EntityClient" />
<add name="FairCreditDatabase" connectionString="Data Source=.;Initial Catalog=FairCreditDev;Integrated Security=False;User=FairCredit;Password=***;MultipleActiveResultSets=True" providerName="System.Data.SqlClient" />
<add name="FairCreditDatabaseElmah" connectionString="Data Source=.;Initial Catalog=FairCreditDev;Integrated Security=False;User=FairCreditElmah;Password=***;MultipleActiveResultSets=True" providerName="System.Data.SqlClient" />
<add name="FairCreditDatabaseAdmin" connectionString="Data Source=.;Initial Catalog=FairCreditDev;Integrated Security=False;User=FairCreditAdmin;Password=***;MultipleActiveResultSets=False" providerName="System.Data.SqlClient" />
```
we use EF db first and MSSQL database.

**Comment by TomasBouda** [comment]
I checked with my colleague and this issue seem to be linked with my machine.
I guess I need to change the famous quote to: "It doesn't work on my machine" :grin:. 
Anyway, feel free to close this issue.
Have a nice day
