### ISSUE TITLE
error asp.net core

### ISSUE THREAD

**Issue by duytv14** [GleamTech/DocumentUltimate#4]
Could not load file or assembly 'PresentationEngine, Version=3.3.0.0, Culture=neutral, PublicKeyToken=a6f3cafa178e6038' or one of its dependencies. The system cannot find the file specified.
    Could not load file or assembly 'WordProcessingEngine, Version=3.2.0.0, Culture=neutral, PublicKeyToken=a6f3cafa178e6038' or one of its dependencies. The system cannot find the file specified.
    Could not load file or assembly 'WordProcessingEngine, Version=3.2.0.0, Culture=neutral, PublicKeyToken=a6f3cafa178e6038' or one of its dependencies. The system cannot find the file specified.
    Could not load file or assembly 'SpreadsheetEngine, Version=3.3.0.0, Culture=neutral, PublicKeyToken=a6f3cafa178e6038' or one of its dependencies. The system cannot find the file specified.

**Comment by GleamTech** [comment]
You can use DocumentUltimate only in a "ASP.NET Core on .NET Framework" project for now. Are you sure you have the correct project type?

> Note that "ASP.NET Core on .NET Core" is a different platform and it's not supported yet because it requires porting all the code from .NET Framework runtime to .NET Core runtime so it requires a new DLL and .NET Core runtime does not provide all of the APIs yet. Minimum supported version is ASP.NET Core MVC 2.0.3 on .NET Framework 4.6.1 (this is because 2.0.3 fixes a bug related to referencing external DLLs in a razor page).

**Comment by duytv14** [comment]
Cảm ơn vì phản hồi của bạn,
Hiện tại tôi đag xây dựng một website bán hàng dựa trên mã nguồn mở nopcommerce 4.0, tôi muốn đưa phẩn hiển thị file để người dùng xem hóa đơn.
