### ISSUE TITLE
Document Cache info is not found issue

### ISSUE THREAD

**Issue by kapilgupta-tml** [GleamTech/DocumentUltimate#7]
When multiple user is trying to access  we are getting "Document Cache info is not found".

**Comment by mantasaudickas** [comment]
Any thoughts, comments from GleamTech?

**Comment by GleamTech** [comment]
Ensure you set DocumentUltimateWebConfiguration properties (e.g. `DocumentUltimateWebConfiguration.Current.CacheLocation`) once in Startup of your application, not everytime you hit a page, it’s a global object it should not be changed concurrently.
