### ISSUE TITLE
DocumentUltimate- Powerpoint files not loading

### ISSUE THREAD

**Issue by JanhaviPore** [GleamTech/DocumentUltimate#8]
I created the sample project for DocumentUltimate as i want to integrate it in my main project. I downloaded the latest version of DocumentUltimatec(5.2.2) and GleamTech.Common dll from Nuget package and followed this same example as given here for AspNet MVC CS
 . All other format files are loading. But the PPT files are not loading. Attached screenshot of the same error. Please reply as soon as possible

![PPt files error](https://user-images.githubusercontent.com/64523768/80574510-995f4b80-8a1f-11ea-92a3-f04a167617d8.png)

**Comment by GleamTech** [comment]
Make sure the extension and format of the file matches, for example it should not be a PPTX file renamed as PPT. There is no known issue with PPT files, did you test other PPT files? Maybe only that specific file has a problem, e.g. corrupted. Also test your files against the live demo:
https://demos.gleamtech.com/documentultimate/
